% SLiMfinderAdapt.m allows you to use excel files generated by part 1 of
% PHASTpep in order to create a file that can be input into SLiMfinder
% software, available
% http://www.southampton.ac.uk/~re1u06/software/packages/slimsuite/
% original publication: 
% Edwards,R., Davey,N., and Shields,D. (2007) SLiMFinder: a probabilistic
% method for identifying over-represented, convergently evolved, short
% linear motifs in proteins. PLoS One., 2, e967
%
% input
%      inputname: string name of variable that you loaded and want to run 
%      in SLiMfinder
%
% output
%      fileoutputname: string name of .fasta file to create
%
% Created by Lindsey Brinton at the University of Virginia, 2016

% brief instructions
% after making files with PHASTpep part 1, go into excel and sort the data
% by column B, largest to smallest
%
% load excel file into MATLAB by clicking on import data and selecting 
% the excel file. This brings up an import window.
% choose the range A1:A200 and "Cell Array." This loads the first 200
% sequences of your data in as a cell variable.

% add filename of cell variable here as input *****************************
inputname = examplecellvariableinput;

% add filename for output file here with the file extension .fasta ********
fileoutputname = 'exampleoutputfile.fasta';

j=1;k=2;
for i=1:200
    data(i).Header = fileinputname{j};
    j=j+2;
end

for i=1:200
    data(i).Sequence = fileinputname{k};
    k=k+2;
end

% write output file
fastawrite(fileoutputname,data);